- name: Deploy to swiftdd.github.io
        env:
          D_T: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git clone "https://x-access-token:${D_T}@github.com/swiftdd/swiftdd.github.io.git" portal_repo
          
          # 同步所有核心展示文件
          cp index.md portal_repo/
          cp index.html portal_repo/
          cp .nojekyll portal_repo/
          rm -rf portal_repo/BACKUP
          cp -r BACKUP portal_repo/
          
          cd portal_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "update: deployment with html renderer"
            git push origin main
          fi
